services:
  codeloom-postgres:
    image: postgres:18.1-alpine3.23
    container_name: codeloom-postgres
    environment:
      POSTGRES_USER: codeloom
      POSTGRES_PASSWORD: codeloom
    ports:
      - 5433:5432
    volumes:
      - ./infra/database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U codeloom -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: codeloom-keycloak
    command: start-dev --import-realm --metrics-enabled=true --verbose
    ports:
      - 8000:8080
      - 9000:9000
    environment:
      JAVA_OPTS: -Dkeycloak.migration.usersExportStrategy=REALM_FILE
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://codeloom-postgres:5432/keycloak
      KC_DB_USERNAME: codeloom
      KC_DB_PASSWORD: codeloom
    volumes:
      - ./infra/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      codeloom-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9000/health/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30


  adminer:
    image: adminer:latest
    container_name: codeloom-adminer
    ports:
      - 8088:8080
    depends_on:
      codeloom-postgres:
        condition: service_healthy

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: codeloom-kafka
    ports:
      - 29092:29092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  # codeloom-backend
  # codeloom-executor
  # codeloom-frontend
