services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    command:
    - start-dev
    ports:
    - 8080:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
    - db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 8080
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: zakat
      KC_DB_PASSWORD: zakat_pwd
  
  db:
    image: postgres:18.1-alpine3.23
    ports:
    - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zakat
      POSTGRES_PASSWORD: zakat_pwd
  
  adminer:
    image: adminer
    ports:
    - 8088:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    ports:
    - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db:
  keycloak_data: