plugins {
    id 'org.jetbrains.kotlin.plugin.spring'
    id 'org.springframework.boot'
}

description = 'Code executor'

dependencies {
    implementation project(':common')

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'com.github.docker-java:docker-java:3.7.1'
    implementation 'com.github.docker-java:docker-java-transport-httpclient5:3.7.1'
    implementation 'org.apache.commons:commons-compress:1.28.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:6.3.0'
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
